name: Regresión Funcional E2E - Portal de Pagos

# 1. El pipeline se activará automáticamente con cada Push a la rama main
on:
  push:
    branches: 
      - main  

jobs:
  automation-test:
    # 2. Corre en una máquina virtual de Ubuntu limpia en la nube
    runs-on: ubuntu-latest
    
    steps:
    # Paso A: Clonar tu repositorio dentro de la máquina de GitHub
    - name: Checkout de código
      uses: actions/checkout@v4
    
    - name: LISTAR ARCHIVOS (DEBUG)
      run: ls -R  # Esto imprimirá toda la estructura de carpetas en el log

    # Paso B: Configurar Java JDK 
    - name: Configurar Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    # Usamos -f para indicar la ruta exacta del archivo
    - name: Levantar Docker
      run: docker compose -f demo/docker-compose.yml up -d

    - name: Esperar servicios
      run: sleep 30 # Tiempo para que Kafka y la App arranquen

    # 3. Instalar dependencias y ejecutar las pruebas en modo Headless
    - name: Ejecutar Pruebas Automatizadas
      run: mvn clean test -Dmaven.compiler.source=21 -Dmaven.compiler.target=21

    # 4. PUNTO EXTRA: Si los tests fallan, guarda el reporte como evidencia
    - name: Subir Reporte de Errores (Artefacto)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: reporte-fallos-qa
        path: demo/target/surefire-reports/
        retention-days: 5